/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/Inventory/Index': RouteRecordInfo<'/Inventory/Index', '/Inventory/Index', Record<never, never>, Record<never, never>>,
    '/Inventory/Logs': RouteRecordInfo<'/Inventory/Logs', '/Inventory/Logs', Record<never, never>, Record<never, never>>,
    '/Inventory/Scan': RouteRecordInfo<'/Inventory/Scan', '/Inventory/Scan', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/Orders/PendingOrderStats': RouteRecordInfo<'/Orders/PendingOrderStats', '/Orders/PendingOrderStats', Record<never, never>, Record<never, never>>,
    '/Orders/PreOrderStats': RouteRecordInfo<'/Orders/PreOrderStats', '/Orders/PreOrderStats', Record<never, never>, Record<never, never>>,
    '/Products/Detail': RouteRecordInfo<'/Products/Detail', '/Products/Detail', Record<never, never>, Record<never, never>>,
    '/Products/Index': RouteRecordInfo<'/Products/Index', '/Products/Index', Record<never, never>, Record<never, never>>,
    '/Products/SalesRanking': RouteRecordInfo<'/Products/SalesRanking', '/Products/SalesRanking', Record<never, never>, Record<never, never>>,
    '/Profile': RouteRecordInfo<'/Profile', '/Profile', Record<never, never>, Record<never, never>>,
    '/Sync/Index': RouteRecordInfo<'/Sync/Index', '/Sync/Index', Record<never, never>, Record<never, never>>,
    '/Users/Index': RouteRecordInfo<'/Users/Index', '/Users/Index', Record<never, never>, Record<never, never>>,
  }
}
